services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword

  gateway:
    build: ./backend/gateway
    container_name: gateway
    command: node gateway.js
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - cata
      - findtop5
      - sharedalbum

  cata:
    build: ./backend/cata
    container_name: cata
    command: python cata.py
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  catb:
    build: ./backend/catb
    container_name: catb
    command: python catb.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  findtop5:
    build: ./backend/findtop5
    container_name: findtop5
    command: python findtop5.py
    ports:
      - "5300:5300"
    environment:
      - RABBITMQ_HOST=rabbitmq

  notification:
    build: ./backend/notification
    container_name: notification
    command: python notification.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  sharedalbum:
    build: ./backend/sharedalbum
    container_name: sharedalbum
    command: python sharedalbum.py
    ports:
      - "5100:5100"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  sharedalbum_eventbroker:
    build: ./backend/sharedalbumeventbroker
    container_name: sharedalbumeventbroker
    command: python sharedalbum_eventbroker.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  videoproc:
    build: ./backend/vidprocrabbmq
    container_name: videoprocrabbmq
    command: python vidprocrabbmq.py
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "8080:80"
    depends_on:
      - gateway
